name: melon-ticket-checker

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: 2026-03-20
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 212676
          schedule-id: 100001
          seat-id: 1_0
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "ğŸ« ì·¨ì†Œí‘œ ê°ì§€! (2026-03-20) ì§€ê¸ˆ ë©œë¡ í‹°ì¼“ í™•ì¸!"

      - name: 2026-03-21
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 212676
          schedule-id: 100002
          seat-id: 1_0
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "ğŸ« ì·¨ì†Œí‘œ ê°ì§€! (2026-03-21) ì§€ê¸ˆ ë©œë¡ í‹°ì¼“ í™•ì¸!"

      - name: 2026-03-22
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 212676
          schedule-id: 100003
          seat-id: 1_0
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "ğŸ« ì·¨ì†Œí‘œ ê°ì§€! (2026-03-22) ì§€ê¸ˆ ë©œë¡ í‹°ì¼“ í™•ì¸!"

      - name: 2026-03-27
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 212676
          schedule-id: 100004
          seat-id: 1_0
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "ğŸ« ì·¨ì†Œí‘œ ê°ì§€! (2026-03-27) ì§€ê¸ˆ ë©œë¡ í‹°ì¼“ í™•ì¸!"

      - name: 2026-03-28
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 212676
          schedule-id: 100005
          seat-id: 1_0
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "ğŸ« ì·¨ì†Œí‘œ ê°ì§€! (2026-03-28) ì§€ê¸ˆ ë©œë¡ í‹°ì¼“ í™•ì¸!"

      - name: 2026-03-29
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 212676
          schedule-id: 100006
          seat-id: 1_0
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "ğŸ« ì·¨ì†Œí‘œ ê°ì§€! (2026-03-29) ì§€ê¸ˆ ë©œë¡ í‹°ì¼“ í™•ì¸!"
